namespace CompiledBindings;

public static class GenerateUtils
{
	public const string GeneratedCodeHeader =
$@"//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
";

	public static string GenerateCompiledBindingsHelperNs(string rootNamespace, string assemblyName, string frameworkId)
	{
		var rgx = new Regex(@"[^a-zA-Z0-9]");
		assemblyName = rgx.Replace(assemblyName, "_");
		if (assemblyName.StartsWith("_"))
		{
			assemblyName = assemblyName.Substring(1);
		}
		return $"{rootNamespace}.{assemblyName}_{frameworkId}";
	}
}
